### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-8: character maps to <undefined>

### ISSUE THREAD

**Issue by scriptcuddle** [thelinuxuser-choice/Mega-Account-Creator#4]
how to fix it bro

$ python mega.py

Traceback (most recent call last):
  File "C:\Users\AbygaileJhonson\mega\mega.py", line 47, in <module>
    print(banner)
  File "C:\Users\AbygaileJhonson\AppData\Local\Programs\Python\Python310\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\AbygaileJhonson\AppData\Local\Programs\Python\Python310\lib\site-packages\colorama\ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "C:\Users\AbygaileJhonson\AppData\Local\Programs\Python\Python310\lib\site-packages\colorama\ansitowin32.py", line 195, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\AbygaileJhonson\AppData\Local\Programs\Python\Python310\lib\site-packages\colorama\ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\AbygaileJhonson\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-8: character maps to <undefined>

**Comment by defaltastra** [comment]
try running `export PYTHONIOENCODING=utf8` in your terminal then running the script again

**Comment by kanjvt** [comment]
> try running `export PYTHONIOENCODING=utf8` in your terminal then running the script again

Traceback (most recent call last):
  File "C:\Users\AbygaileJhonson\Desktop\Mega-Account-Creator\mega.py", line 55, in <module>
    driver = webdriver.Chrome(path)
  File "C:\Users\AbygaileJhonson\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\AbygaileJhonson\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\AbygaileJhonson\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by scriptcuddle** [comment]
> try running `export PYTHONIOENCODING=utf8` in your terminal then running the script again

[Error] An error occured while Creating a Account Reasons are [Names you have entered in emails.txt is taken]
[EXIT] Press Enter to Exit >[16720:9804:0809/215905.527:ERROR:util.cc(127)] Can't create base directory: C:\Program Files\Google\GoogleUpdater

**Comment by defaltastra** [comment]
you have to go to emails.txt and generate usernames using the link http://generator.my-addr.com/generate_usernames-free_username_generator_online_tool.php then paste them there and try again, also make sure to have google chrome installed

**Comment by scriptcuddle** [comment]
> you have to go to emails.txt and generate usernames using the link http://generator.my-addr.com/generate_usernames-free_username_generator_online_tool.php then paste them there and try again, also make sure to have google chrome installed

i did it bro, the results are the same, what version of the chrome driver are you use?
